- name: Install Snort Dependency
  become: yes
  apt:
    name: 
    - libpcre3-dev
    - zlib1g-dev
    - libluajit-5.1-dev
    - libpcap-dev
    - openssl
    - libssl-dev
    - libnghttp2-dev
    - libdumbnet-dev
    - bison
    - flex
    - libdnet
    - autoconf
    - libtool

- name: Download Snort
  get_url: 
    url: https://www.snort.org/downloads/snort/snort-2.9.17.tar.gz
    dest: /tmp
  register: download_snort

- name: Untar Snort
  become: yes
  unarchive:
    src: /tmp/snort-2.9.17.tar.gz
    dest: /home/ubuntu/snort
    copy: no
  when: download_snort.changed
  register: untar_snort

- name: Install Snort
  command: chdir=/home/ubuntu/snort/snort-2.9.17 {{item}}
  become: yes
  with_items:
  - "./configure --enable-sourcefire"
  - "/usr/bin/make"
  - "/usr/bin/make install"
  - "ldconfig"
  when: untar_snort.changed
  register: install_snort

# - name: Create Snort symlink
#   become: yes
#   file: src=/usr/local/bin/snort dest=/usr/sbin/snort state=link