---
- name: Amazon test
  hosts: localhost
  vars:
    ansible_become: yes
    ansible_become_method: sudo  
    ansible_become_password: "password"
  roles:
  # - common
  - python
  - snort
  - slack